const NAME = "NAME";
const FAMILY = "FAMILY";
const USERNAME = "USERNAME";
const EMAIL = "EMAIL";
const PHONE = "PHONE";
const BIRTHDAY = "BIRTHDAY";
const PASSWORD = "PASSWORD";
const NEW_PASSWORD = "NEW_PASSWORD";
const ALL = "ALL";

export {
  NAME,
  FAMILY,
  USERNAME,
  EMAIL,
  PHONE,
  BIRTHDAY,
  PASSWORD,
  NEW_PASSWORD,
  ALL,
};
